app:
    resource: '@AppBundle/Controller/'
    type: annotation

velo:
    resource: "@VeloBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


